name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        registry-url: ['https://registry.npmjs.org']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ matrix.registry-url }}
      - name: 'Installing TypeScript globally'
        run: npm i -g typescript
      - name: 'Installing deps'
        run: npm i
      - name: 'Publish'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}